import type { Metadata } from "next";
import "./globals.css";
import SideBarNav from "./components/sidebar/side-nav-bar";
import Header from "./components/header";
import ProfileBadge from "./components/sidebar/profile-badge";
import localFont from 'next/font/local'

const myFont = localFont({
  src: '../fonts/gg-sans-2/gg sans Regular.ttf',
})


export const metadata: Metadata = {
  title: "Discord App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} font-gg-sans w-full antialiased h-screen overflow-hidden relative bg-black`}
      >
        <Header/>
        <div className="w-full h-full flex flex-row"><SideBarNav/>
        
          {children}
        </div>
        <ProfileBadge/>
        
       
      </body>
    </html>
  );
}
