import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBarNav from "./components/side-nav-bar";
import Header from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full antialiased h-screen overflow-hidden grid grid-cols-4 bg-black`}
      >
        <Header/>
        <SideBarNav/>
        <div className="w-full col-span-3 bg-zinc-800">
          {children}
        </div>
       
      </body>
    </html>
  );
}
